#!/bin/bash

for test in build/test_*
do
  echo -n "Running `basename $test...`"
  output=$($test 2>&1)
  if [ $? -ne 0 ]; then 
    echo "FAILED:"
    echo $output
    exit 1
  else
    echo "OK"
  fi
done
